---
title: "Trial mortality predictions - UKCTOCS"
author: "Lukas Owens"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
library(tidyverse)
source('core.R')
```

### Inputs and staging

Values taken from published trial: 
  https://pubmed.ncbi.nlm.nih.gov/33991479/

```{r}

# Read total cases and death count by arm extracted from trial
trial_counts <- read_csv('../data/trial-data-ukctocs.csv')

# Subjects were followed for 19.25 years (from April 2001 to June 2020)
trial_length <- 19.25

# Person-years in each arm (from Table 1)
py_ctrl   <- 1577517
py_screen <- 789129

# Define early vs late stage disease
earlylate <- tribble(
  ~stage, ~late,
  'I',    'E',  
  'II',   'A',    
  'III',  'A',    
  'IV',   'A'     
)

# Actual observed mortality reduction (and upper/lower CI bounds)
actual <- 0.04
lb <- -0.10
ub <- 0.17

```


Group and summarize by early/advanced stage definition
```{r}
trial_counts_ea <- trial_counts %>% 
  left_join(earlylate) %>%
  group_by(arm, late) %>%
  summarise(cases = sum(cases), deaths = sum(deaths)) %>%
  mutate(case_dist = cases / sum(cases), fatality_rate = deaths / cases)
trial_counts_ea
```

### Model calculations
Calculate incidence rate ($\lambda_d$), rate of late-stage cancer ($p_1$) and reduction in late-stage ($\alpha$)
```{r}
lambda_d <- sum(trial_counts_ea %>% filter(arm=='control') %>% pull(cases)) / py_ctrl
lambda_d

adv_cases_ctrl   <- trial_counts_ea %>% filter(arm=='control', late=='A') %>% pull(cases)
adv_cases_screen <- trial_counts_ea %>% filter(arm=='screen', late=='A') %>% pull(cases)
alpha <- 1 - (adv_cases_screen / py_screen) / (adv_cases_ctrl / py_ctrl)
alpha

p_1 <- trial_counts_ea %>% filter(arm=='control', late=='A') %>% pull(case_dist)
p_1
```
Calculate mortality hazards ($\lambda_0$ and $\lambda_1$) implied by case fatality rates in data. 
```{r}

calc_mortality_rates <- function(ea) {
  fatality_rate <- trial_counts_ea %>% filter(arm == 'control', late==ea) %>% pull(fatality_rate)
  total_cases <- trial_counts_ea %>% filter(arm == 'control', late==ea) %>% pull(cases)
  case_hazard <- total_cases / py_ctrl 
  
  # Formula for calculating fatality rate from above inputs and a given mortality hazard
  fatality_rate_fn <- function(mort_hazard) {
    (1-(mort_hazard*exp(-case_hazard*trial_length) - case_hazard*exp(-mort_hazard*trial_length)) / (mort_hazard - case_hazard)) / (1-exp(-case_hazard*trial_length))
  }
    
  
  # Determine mortality rate that achieves observed fatality rate 
  f <- function(x) abs(fatality_rate_fn(x) - fatality_rate)
  return(optimize(f, lower=0, upper=5)$minimum)
}
lambda_0 <- calc_mortality_rates('E')
lambda_1 <- calc_mortality_rates('A')

```


### Final calculations

```{r}
r_0 <- calc_r(trial_length, lambda_d, lambda_0)
r_1 <- calc_r(trial_length, lambda_d, lambda_1)
rho <- calc_rho(trial_length, r_0, r_1, p_1)
mrel <- rho * alpha

output <- tribble(
  ~trial, ~lambda_d, ~lambda_0, ~lambda_1, ~p_1, ~rho, ~alpha, ~mrel, ~actual, ~lb, ~ub,
  'ukctocs', lambda_d, lambda_0, lambda_1, p_1, rho, alpha, mrel, actual, lb, ub
)
output
write_csv(output, '../output/trial-calculations-ukctocs.csv')
```


